### ISSUE TITLE
Compatibility Firefox Nightly

### ISSUE THREAD

**Issue by nbraud** [sibiantony/ssleuth#17]
On Firefox Nightly (Linux amd64, 2015-01-16, e10s enabled), I am having two issues with ssleuth (both commit 686f083cdebad9134723b0ec98e61f05c4ca9448 and the latest release):
- the TLS version in use isn't displayed;
- the preferences page is blank.

What may I do to help debug these issues?

**Comment by sibiantony** [comment]
Okay. Noticed preferences page and domains tab problems with e10s. Never got enough time to look into the problem.
But I don't see anything wrong with TLS version display. [ 38.0a1 (2015-01-21) - e10s enabled ]
The problem with the preferences page/domains could be due to the way the tab ids are stored in SSleuth. Those are expando properties set for the `browser` element. There are exceptions at `SSleuthHttpObserver.getTab`. 
I will have a look and get back with fix/more pointers.

**Comment by nbraud** [comment]
Thanks a lot :-)

**Comment by rugk** [comment]
BTW please submit this add-on to http://arewee10syet.com/ so that everyone knows whether the add-on is compatible with e10s.

**Comment by sibiantony** [comment]
@rugk there are some incompatibilities to be addressed before supporting e10s. Sorry about the delay.

**Comment by sibiantony** [comment]
Version 0.5.1 released with support for e10s. Closing the issue.
