### ISSUE TITLE
Compatibility with Firefox Nightly 41.0a1

### ISSUE THREAD

**Issue by bknowles** [sibiantony/ssleuth#20]
So, I'm using Nightly 41.0a1 (2015-05-18), and it's not clear to me how I could download the latest test version of SSleuth, which would hopefully work.  Are there any instructions anywhere that I could follow?

Thanks!

**Comment by sibiantony** [comment]
Hi. As of now the latest code in master branch is already released, and is avaialable for download from addons.mozilla.org
If you simply wish to play around with the code either fork the code (github.com help) or just git clone on to a local repo and point firefox to the extension directory.  You'll find plenty of tutorials online on how to load a firefox extension from source directory instead of an xpi installation. 
If you're looking for compatibility with e10s then I'm tracking that in #17

**Comment by bknowles** [comment]
Ironically, I had found #17 and chose to open a separate ticket on this issue instead of posting my question there.

So, yes -- that answers my question.  Thanks!
