### ISSUE TITLE
Unsafe CPOW usage - e10s

### ISSUE THREAD

**Issue by chinaar** [sibiantony/ssleuth#29]
On the latest nightly (2015-06-01) I am seeing repeated unsafe CPOW accesses as shown below. This is definitely not an urgent issue as it doesn't impede functionality, but can impede performance. 

![unsafe-cpow](https://cloud.githubusercontent.com/assets/10645442/7928948/a6d50b5e-092a-11e5-8e7b-d5ab40971f56.jpg)

This could be the cause of the delay in changing scores when changing tab. If I load one tab and then switch to another, sometimes the score of the previous website is shown on the new tab, even if it isn't secure. This will correct itself if the new tab finishes loading, or if I refresh the page, but will remain if the page fails to load. The score shown below, is actually the score for Github, but here it is shown for the unsecured scriptish blog. The scriptish page had at that time failed to load.
 
![untitled-1](https://cloud.githubusercontent.com/assets/10645442/7929000/61ffbe42-092b-11e5-80c7-0db73b394b27.jpg)

Thanks for your hard work on this extension.

**Comment by sibiantony** [comment]
The e10s compatibility issues are tracked in #17 . Which requires some rewrite to implement a message manager etc.
The above problem seems to be due to the failure in loading of the second tab (scriptish.org) and probably not due to performance/slowness. Most likely in the above case SSleuth doesn't get the stateChange event from Firefox, and hence no way to change the notifier/info. 
Will see if there are any workarounds in this case, too busy with other stuff, please expect some delay.

**Comment by sibiantony** [comment]
Version 0.5.1 released with support for e10s. Closing the issue.
