### ISSUE TITLE
URL red/green color gradient should be alpha transparent

### ISSUE THREAD

**Issue by tr37ion** [sibiantony/ssleuth#66]
Please consider making the _red/green URL addressbar color gradient overlay_ alpha transparent, so that it suites Firefox Developer's dark themes, too.

With SSLeuth:
![With SSLeuth](https://cloud.githubusercontent.com/assets/1538617/18411234/d6210210-7773-11e6-8c2f-afa4de50d1f5.png)

Without SSLeuth:
![Without SSLeuth](https://cloud.githubusercontent.com/assets/1538617/18411236/dac60022-7773-11e6-9156-9793e1b6e9ce.png)

**Comment by sibiantony** [comment]
This will happen only if you enable url bar 'Colorize' option and was intentional.  If the option is turned off, the urlbar will be back to as it was. 
With the colorizing and a gradient on alpha transparency, the url text become unable to read (esp. with blue/red etc), and people had reported issues on that. Later it was decided to have a gradient with uniform white background if user selects the option. 

If you don't have anything more to add, I'll close the issue

**Comment by sibiantony** [comment]
Closing the issue. Please disable the 'colorize' option if necessary.
