### ISSUE TITLE
Lower score when Cloudflare certificate is used

### ISSUE THREAD

**Issue by rugk** [sibiantony/ssleuth#76]
First read:
- https://scotthelme.co.uk/cloudflares-great-new-features-and-why-i-wont-use-them/
- Practical example: https://medium.com/@karthikb351/airtel-is-sniffing-and-censoring-cloudflares-traffic-in-india-and-they-don-t-even-know-it-90935f7f6d98#.hz4zd6hv6

So as you see in the default setting the TLS connection ends at Cloudflare and Cloudflare seriously fetches unverified & unencrypted content over HTTP and makes it available over HTTPS.
Of course web admins can slightly (or even better not so slightly) improve security by enabling other modes and deploy a cert on their own server, but personally I doubt many people do this. Most might just think: "Hey, all right. We now use HTTPS, so this is secure."

Unfortunately AFAIK Cloudflare still provides no method to get out what SSL/TLS mode is used.
Anyway I'd suggest you lower the score and/or - at least - show a warning, so users are made aware of this.
It's easy to detect Cloudflare certificates as they are issued for (CN) "[...].cloudflaressl.com".

**Comment by jeifour** [comment]
TLS does not mean that your data is safe. It means that your connection to a certain server is safe, and that the data you send over that one connection therefore won't get out to a third party by doing so, but what happens to it after you sent it is out of your hands. So I don't think this is an issue SSleuth should be concerned with. (Not saying this isn't a more general problem, of course.)

What makes you distrust a connection to a Cloudflare server, but trust all the other TLS connections to other servers? Alright, maybe you're very sure that your bank knows how to security is done right, and you're also sure websites like Github know how to secure their customer data because they certainly employ technically skilled people, and that, I'd reckon, is also probably the truth, but then the only thing maybe useful would be a Whitelist for trusted parties, and not a Blacklist with a single entry titled "Cloudflare". (And then there are some websites using Cloudflare that might even have a secure configuration after all, so the warning wouldn't be appropriate then.)

If most people think "Hey, all right. We now use HTTPS, so this is secure.", then that in itself is the problem. With Cloudflare just being a good example of why, not a singular instance of failure. I don't doubt they indeed think like this, but lowering the score for Cloudflare is not the correct way of handling that problem in my opinion. If anything, maybe educating users should look something like: "TLS only secures your browser's connection to web servers, it isn't a guarantee for secure and/or lawful handling of inputted data." (I'm not a native speaker so the phrasing is probably off, but I hope you get my drift.)

Side note: Interesting articles, thanks for linking them. I actually have thought about this problem a few times before but didn't follow up on any news about it.

**Comment by sibiantony** [comment]
@rugk in above post jeifor summed up pretty much what I wanted to say. 
This add-on was created with the idea to present to the user the technical data on the TLS connection, in a simpler/open way. Almost all of what you see is what is obtained from Mozilla APIs. The only addition being the score out of 10, which is computed based on the TLS parameters and the certificate. And I wish to keep it that way, without making 'judgements' about who is running what on an SSL/TLS connection.

What you're suggesting is to introduce a 'trust' grading for a specific service provider. And that is not in the scope of this project. Perhaps that might fit for [Web of Trust](https://addons.mozilla.org/en-US/firefox/addon/wot-safe-browsing-tool/) project.

If you don't have anything more to add, please close this. 

> Hey, all right. We now use HTTPS, so this is secure.

Here, people need to be educated on the definition of being 'secure'. There are known to have malwares and phishing scams hosted on https sites. And TLS is not be blamed for that.
